# Site settings
title: Wombats Learning
email: yacht2005@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/wombats-learning" # the subpath of your site, e.g. /blog/
url: "http://maomaoliu.github.io/wombats-learning/" # the base hostname & protocol for your site
github_username:  maomaoliu

# Build settings
markdown: kramdown
