# Site settings
title: Wombats Learning
description: Anyone who stops learning is old.
baseurl: "/wombats-learning"
url: "http://maomaoliu.github.io/wombats-learning/"

# Build settings
markdown: kramdown
